FROM registry.fedoraproject.org/fedora-toolbox:40

ARG NAME=development-fedora-toolbox
ARG VERSION=40

LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Image for creating Fedora Toolbx containers"

# Shell
RUN dnf -y install zsh vim htop net-tools

# Container Stuff
ENV CONTAINER_HOST=unix:///run/user/1000/podman/toolbox-development-podman.sock
ENV DOCKER_HOST=${CONTAINER_HOST}
RUN dnf -y install podman-remote docker-compose
RUN ln -s /usr/bin/podman-remote /usr/bin/podman
RUN ln -s /usr/bin/podman /usr/bin/docker

# Development
RUN dnf -y install adoptium-temurin-java-repository
RUN dnf -y config-manager --set-enabled adoptium-temurin-java-repository
RUN dnf -y install make golang temurin-11-jdk temurin-17-jdk ansible ansible-lint python3-netaddr

# vscode
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/vscode.repo > /dev/null
RUN dnf -y install code

# gcloud
RUN echo -e "[google-cloud-cli]\nname=Google Cloud CLI\nbaseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=0\ngpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg" | tee -a /etc/yum.repos.d/google-cloud-sdk.repo
RUN dnf -y install google-cloud-cli google-cloud-cli-gke-gcloud-auth-plugin

# Kubernetes
RUN dnf -y install kubectl helm

# Terraform
RUN dnf install -y dnf-plugins-core
RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
RUN dnf -y install terraform

# Copy rootfs
COPY rootfs/ /

RUN dnf clean all
